'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { saveDefinition, setPublication, restoreDefinition } from '@/app/admin/actions';
import { editableDefinitionSchema, parseUpload, type EditableDefinition } from '@/lib/admin-validation';

export function AdminEditor({initial,id,revision,status,history}:{initial:EditableDefinition;id?:string;revision:number;status?:'draft'|'published'|'archived';history:{id:string;version:string;createdAt:string}[]}){
  const router=useRouter();const [value,setValue]=useState(initial);const [pending,setPending]=useState(false);const [message,setMessage]=useState('');const [preview,setPreview]=useState(false);const [currentId,setCurrentId]=useState(id);const [currentRevision,setCurrentRevision]=useState(revision);
  function update(key:keyof EditableDefinition,next:string|string[]){setValue(previous=>({...previous,[key]:next}));setPreview(false);}
  async function visibility(next:'draft'|'archived'|'published'){
    if(!currentId)return;setPending(true);setMessage('');try{const result=await setPublication(currentId,next);setMessage(result.error??result.success??'');router.refresh();}catch{setMessage('Unable to change visibility. Try again.');}finally{setPending(false);}
  }
  return <section className="page-shell admin-page"><Link className="back" href="/admin">← Admin library</Link><div className="eyebrow">{currentId?'EDIT DEFINITION':'NEW DEFINITION'} / {status??'DRAFT'}</div><h1>{currentId?'Refine your piece.':'Add a new piece.'}</h1><p className="intro">Save changes privately, preview the definition, then publish a new version.</p>
    <form className="admin-editor" onSubmit={async event=>{
      event.preventDefault();const intent=(event.nativeEvent as SubmitEvent).submitter?.getAttribute('data-intent');setMessage('');
      const parsed=editableDefinitionSchema.safeParse({...value,inputs:value.inputs.map(line=>line.trim()).filter(Boolean),outputs:value.outputs.map(line=>line.trim()).filter(Boolean),stages:value.stages.map(line=>line.trim()).filter(Boolean)});if(!parsed.success){setMessage(parsed.error.issues.map(issue=>`${issue.path.join('.')}: ${issue.message}`).join('; '));return;}
      if(intent==='preview'){setPreview(true);return;}
      setPending(true);try{const result=await saveDefinition(parsed.data,currentId,currentRevision,intent==='publish');if(result.id){setCurrentId(result.id);setCurrentRevision(result.revision??currentRevision);router.replace(`/admin/${result.id}`);}setMessage(result.error??result.success??'');router.refresh();}catch{setMessage('Unable to save. Please try again.');}finally{setPending(false);}
    }}><fieldset disabled={pending}>
      <div className="admin-upload"><label>Upload a definition<input type="file" accept=".json,.md,.txt" onChange={async event=>{
        const file=event.currentTarget.files?.[0];if(!file)return;setMessage('');try{if(file.size>200000)throw new Error('Files must be smaller than 200 KB.');const uploaded=parseUpload(await file.text(),file.name,value);if(currentId&&(uploaded.slug!==value.slug||uploaded.kind!==value.kind))throw new Error('This upload must match the existing slug and type. Create a new item for a different definition.');setValue(uploaded);setPreview(false);setMessage(/\.json$/i.test(file.name)?'Definition loaded. Review it, then save a draft.':'Instructions loaded. Fill in the structured fields before saving.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to read this file.');}finally{event.target.value='';}
      }}/></label><p>JSON imports the fields below. Markdown and text files become the instructions. Uploads stay private until published.</p><a className="auth-switch" download="tess-definition.json" href={`data:application/json;charset=utf-8,${encodeURIComponent(JSON.stringify({...value,slug:value.slug||'my-skill',name:value.name||'My skill',description:value.description||'What this skill does',category:value.category||'Research',inputs:value.inputs.length?value.inputs:['Required input'],outputs:value.outputs.length?value.outputs:['Expected output'],stages:value.stages.length?value.stages:['Describe the process'],limitations:value.limitations||'Known limitations'},null,2))}`}>Download JSON template</a></div>
      <div className="admin-fields"><label>Name<input required maxLength={150} value={value.name} onChange={event=>update('name',event.target.value)}/></label><label>Type<select disabled={Boolean(currentId)} value={value.kind} onChange={event=>update('kind',event.target.value)}><option value="skill">Skill</option><option value="loop">Loop</option></select></label><label>Slug<input required disabled={Boolean(currentId)} maxLength={100} placeholder="my-skill" value={value.slug} onChange={event=>update('slug',event.target.value)}/></label><label>Version<input required placeholder="0.1.0" value={value.version} onChange={event=>update('version',event.target.value)}/></label><label>Category<input required maxLength={80} value={value.category} onChange={event=>update('category',event.target.value)}/></label><label>Related skill or loop slug<input maxLength={100} value={value.related} onChange={event=>update('related',event.target.value)}/></label></div>
      <label>Description<textarea required maxLength={1000} rows={3} value={value.description} onChange={event=>update('description',event.target.value)}/></label>
      <div className="admin-fields">{(['inputs','outputs','stages'] as const).map(key=><label key={key}>{key==='stages'?'Process / stages':key==='inputs'?'Inputs':'Outputs'} <small>One item per line</small><textarea required rows={5} value={value[key].join('\n')} onChange={event=>update(key,event.target.value.split('\n'))}/></label>)}</div>
      {(['instructions','tools','conditions','termination','examples','limitations'] as const).map(key=><label key={key}>{({instructions:'Instructions / uploaded content',tools:'Required tools',conditions:'Conditions',termination:'Termination criteria',examples:'Examples',limitations:'Known limitations'})[key]}<textarea required={key==='limitations'} rows={key==='instructions'?10:3} maxLength={key==='instructions'?100000:key==='examples'?20000:key==='limitations'?10000:5000} value={value[key]??''} onChange={event=>update(key,event.target.value)}/></label>)}
      <div className="notice">Publishing creates an immutable version. Uploads and edits do not mark a definition as tested; evaluations remain attached to their original version.</div>
      <div className="admin-buttons"><button className="button secondary" data-intent="save">Save draft</button><button className="button secondary" data-intent="preview">Preview</button><button className="button" data-intent="publish">Save & publish</button></div>
    </fieldset></form><p className="admin-message" role="status" aria-live="polite">{pending?'Saving…':message}</p>
    {preview&&<section className="admin-preview"><div className="eyebrow">PRIVATE PREVIEW / NOT PUBLISHED</div><h2>{value.name}</h2><p>{value.description}</p><div className="notice">{value.kind} · {value.category} · v{value.version} · No evaluation evidence for this draft</div>{(['inputs','outputs','stages'] as const).map(key=><div key={key}><h3>{key}</h3><ul>{value[key].map((line,index)=><li key={index}>{line}</li>)}</ul></div>)}{(['instructions','tools','conditions','termination','examples','limitations'] as const).map(key=>value[key]&&<div key={key}><h3>{key}</h3><pre>{value[key]}</pre></div>)}</section>}
    {currentId&&<section className="admin-history"><h2>Publishing & history</h2><p>Visibility: {status??'draft'}. Unpublishing and archiving preserve versions and evaluation evidence.</p><div className="admin-buttons">{status==='published'?<button disabled={pending} className="button secondary" onClick={()=>visibility('draft')}>Unpublish</button>:history.length>0&&<button disabled={pending} className="button secondary" onClick={()=>visibility('published')}>Republish current version</button>}{status!=='archived'&&<button disabled={pending} className="button secondary" onClick={()=>visibility('archived')}>Archive</button>}</div>{!history.length&&<p>No published versions yet.</p>}{history.map(row=><div className="admin-row" key={row.id}><span>v{row.version} · {row.createdAt.slice(0,10)}</span><button className="auth-switch" disabled={pending} onClick={async()=>{setPending(true);try{const result=await restoreDefinition(currentId,row.id,currentRevision);setMessage(result.error??result.success??'');router.refresh();}catch{setMessage('Unable to restore this version.');}finally{setPending(false);}}}>Restore as draft</button></div>)}</section>}
  </section>;
}
