import { z } from 'zod';
export const definitionSchema=z.object({slug:z.string(),name:z.string(),description:z.string(),category:z.string(),kind:z.enum(['skill','loop']),inputs:z.array(z.string()),outputs:z.array(z.string()),stages:z.array(z.string()),limitations:z.string(),related:z.string(),version:z.string(),instructions:z.string().optional(),examples:z.string().optional(),tools:z.string().optional(),conditions:z.string().optional(),termination:z.string().optional(),evaluationCount:z.number().int().nonnegative().default(0)});
export type Definition=z.infer<typeof definitionSchema>;
export const definitions:Definition[]=z.array(definitionSchema).parse([
{slug:'source-research',name:'Source research',description:'Turn an open question into a structured brief grounded in traceable sources.',category:'Research',kind:'skill',inputs:['Research question and scope','Source preferences and date range'],outputs:['Evidence brief with source links','Unresolved questions and confidence notes'],stages:['Define the question and scope','Collect relevant primary sources','Extract evidence and record citations','Summarize findings and flag uncertainty'],limitations:'Coverage depends on source access. Conflicting or outdated evidence needs human review. No evaluation runs have been recorded.',related:'research-verify-refine',version:'0.1.0'},
{slug:'document-extraction',name:'Document extraction',description:'Extract useful facts from unstructured documents into a consistent schema.',category:'Data',kind:'skill',inputs:['Document text','Target field schema'],outputs:['Structured fields','Missing fields and supporting excerpts'],stages:['Inspect document structure','Map evidence to the requested fields','Validate types and required fields','Return missing values explicitly'],limitations:'Scanned documents require OCR. Ambiguous fields should remain unresolved instead of being guessed. No evaluation runs have been recorded.',related:'attempt-inspect-retry',version:'0.1.0'},
{slug:'role-fit-analysis',name:'Role fit analysis',description:'Compare a candidate profile with a role’s requirements, with evidence for every match.',category:'Career',kind:'skill',inputs:['Candidate profile','Job description'],outputs:['Requirement-by-requirement comparison','Strengths, gaps, and unanswered questions'],stages:['Identify explicit role requirements','Map candidate evidence to each requirement','Separate supported matches from gaps','Write a concise fit assessment'],limitations:'A fit assessment cannot predict hiring outcomes. Profile quality affects results. No evaluation runs have been recorded.',related:'generate-critique-improve',version:'0.1.0'},
{slug:'brief-writing',name:'Brief writing',description:'Transform verified findings into a clear, audience-specific written brief.',category:'Writing',kind:'skill',inputs:['Verified findings','Audience and desired format'],outputs:['Structured draft','Source references and open issues'],stages:['Identify the audience and key message','Outline the evidence','Draft concise sections','Check statements against source material'],limitations:'Requires source review before publishing. Tone and interpretation may need revision. No evaluation runs have been recorded.',related:'generate-critique-improve',version:'0.1.0'},
{slug:'research-verify-refine',name:'Research → Verify → Refine',description:'Keep improving a research brief until its claims are supported or its limits are explicit.',category:'Evidence',kind:'loop',inputs:['Research question','Evidence criteria and iteration limit'],outputs:['Reviewed brief','Unresolved claims and iteration log'],stages:['Research — gather sources and draft findings','Verify — check each claim against evidence','Refine — revise gaps and contradictions','Stop — criteria met or iteration limit reached'],limitations:'Stop after three iterations by default. Surface unresolved claims when sources are unavailable; never silently treat them as verified.',related:'source-research',version:'0.1.0'},
{slug:'generate-critique-improve',name:'Generate → Critique → Improve',description:'Give a draft a deliberate review cycle against clear acceptance criteria.',category:'Quality',kind:'loop',inputs:['Task and draft requirements','Review rubric and iteration limit'],outputs:['Revised draft','Review notes and outstanding issues'],stages:['Generate — create a first draft','Critique — compare it with the rubric','Improve — address specific issues','Stop — rubric satisfied or three cycles reached'],limitations:'Self-review can miss the same errors as generation. Human review remains useful for subjective or consequential content.',related:'brief-writing',version:'0.1.0'},
{slug:'attempt-inspect-retry',name:'Attempt → Inspect → Retry',description:'Recover from a failed step with bounded retries and an explicit stopping point.',category:'Recovery',kind:'loop',inputs:['Task and success condition','Retry budget'],outputs:['Result or explicit failure','Attempt log'],stages:['Attempt — execute one bounded step','Inspect — validate output and classify failure','Retry — change the approach when appropriate','Stop — success, non-retryable failure, or budget exhausted'],limitations:'Default budget: two retries. Never retry irreversible actions automatically. Stop on missing permission or invalid inputs.',related:'document-extraction',version:'0.1.0'}]);
export const findDefinition=(slug:string)=>definitions.find(x=>x.slug===slug);
