import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { drizzle } from 'drizzle-orm/pglite';
import { migrate } from 'drizzle-orm/pglite/migrator';
import { and, eq } from 'drizzle-orm';
import * as schema from './schema';
import { definitions } from '../lib/content';
import { editableDefinitionSchema, isAdminIdentity, parseUpload } from '../lib/admin-validation';
import { changePublication, publishDraft, readEditor, restoreVersion, saveDraft } from './library-admin';
import { readEvaluations } from './read-evaluations';

assert.equal(isAdminIdentity(null,'owner@example.com'),false);
assert.equal(isAdminIdentity({email:'owner@example.com',emailVerified:false},'owner@example.com'),false,'unverified emails never grant access');
assert.equal(isAdminIdentity({email:'other@example.com',emailVerified:true},'owner@example.com'),false);
assert.equal(isAdminIdentity({email:'owner@example.com',emailVerified:true},undefined),false);
assert.equal(isAdminIdentity({email:'Owner@example.com',emailVerified:true},' owner@example.com '),true);
const definition=editableDefinitionSchema.parse({...definitions[0],slug:'admin-test-piece',name:'Test piece',instructions:'# Instructions\nReview the sources.',evaluationCount:99,testingStatus:'evaluated'});
assert.ok(!('evaluationCount' in definition)&&!('testingStatus' in definition),'upload cannot supply evaluation claims');
assert.equal(parseUpload('# Raw Markdown\n<script>alert(1)</script>','SKILL.md',definition).instructions,'# Raw Markdown\n<script>alert(1)</script>');
assert.deepEqual(parseUpload(JSON.stringify(definition),'piece.json',definition),definition);
assert.throws(()=>parseUpload('{}','piece.json',definition));
assert.throws(()=>parseUpload('x'.repeat(200001),'piece.md',definition));
assert.throws(()=>parseUpload('text','piece.exe',definition));
assert.throws(()=>editableDefinitionSchema.parse({...definition,slug:'../bad'}));
const client=await PGlite.create();const db=drizzle(client,{schema});
try{
  await migrate(db,{migrationsFolder:'./db/migrations'});await migrate(db,{migrationsFolder:'./db/migrations'});
  const actor='synthetic-owner';const saved=await saveDraft(db,actor,definition);
  assert.equal((await db.select().from(schema.versions)).length,0,'saving a new draft does not publish');
  assert.equal((await db.select().from(schema.entries))[0].publicationStatus,'draft');
  await assert.rejects(saveDraft(db,actor,definition),/slug already exists/);
  await assert.rejects(changePublication(db,actor,saved.id,'published'),/Publish a saved draft/);
  await publishDraft(db,actor,saved.id,saved.revision);
  const [original]=await db.select().from(schema.versions);assert.equal(original.version,'0.1.0');
  assert.equal((await db.select().from(schema.entries))[0].publicationStatus,'published');
  await db.insert(schema.evaluations).values({versionId:original.id,method:'Synthetic test evidence',results:{passed:false},limitations:'Disposable test only'});
  const editor=await readEditor(db,saved.id);assert.ok(editor);assert.equal(editor.definition.version,'0.1.1');
  await assert.rejects(saveDraft(db,actor,{...definition,name:'Stale edit'},saved.id,saved.revision),/Another edit/,'publishing must invalidate stale forms');
  const next={...editor.definition,name:'Edited piece',instructions:'Edited instructions'};
  const edited=await saveDraft(db,actor,next,saved.id,editor.revision);
  assert.equal((await db.select().from(schema.entries))[0].name,'Test piece','draft changes do not alter the public title');
  assert.deepEqual((await db.select().from(schema.versions))[0].definition,definition,'published content is immutable');
  await assert.rejects(saveDraft(db,actor,next,saved.id,editor.revision),/Another edit/);
  await assert.rejects(saveDraft(db,actor,{...next,slug:'renamed'},saved.id,edited.revision),/slug and type/);
  await publishDraft(db,actor,saved.id,edited.revision);
  assert.equal((await db.select().from(schema.entries))[0].name,'Edited piece');
  assert.equal((await db.select().from(schema.versions)).length,2);
  const records=await readEvaluations(db,definition.slug);assert.equal(records[0].version,'0.1.0');assert.deepEqual(records[0].results,{passed:false});
  const current=await readEditor(db,saved.id);assert.ok(current);
  const collision=await saveDraft(db,actor,definition,saved.id,current.revision);
  await assert.rejects(publishDraft(db,actor,saved.id,collision.revision),/already been published/);
  assert.equal((await db.select().from(schema.entries))[0].currentVersion,'0.1.1','failed publication preserves current version');
  assert.equal((await db.select().from(schema.drafts)).length,1,'failed publication retains the draft');
  await restoreVersion(db,actor,saved.id,original.id,collision.revision);
  const restored=await readEditor(db,saved.id);assert.ok(restored);assert.equal(restored.definition.name,'Test piece');assert.equal(restored.definition.version,'0.1.2');
  await publishDraft(db,actor,saved.id,restored.revision);
  assert.equal((await db.select().from(schema.versions)).length,3);
  await changePublication(db,actor,saved.id,'draft');
  assert.equal((await db.select().from(schema.entries).where(and(eq(schema.entries.slug,definition.slug),eq(schema.entries.publicationStatus,'published')))).length,0);
  await changePublication(db,actor,saved.id,'archived');assert.equal((await db.select().from(schema.entries))[0].publicationStatus,'archived');
  assert.equal((await readEvaluations(db,definition.slug)).length,1,'archive does not erase evidence');
  await changePublication(db,actor,saved.id,'published');assert.equal((await db.select().from(schema.entries))[0].publicationStatus,'published');
  const loop=await saveDraft(db,actor,{...definition,slug:'test-loop',kind:'loop',conditions:'Until reviewed',termination:'Stop after three attempts'});await publishDraft(db,actor,loop.id,loop.revision);
  assert.equal((await db.select().from(schema.adminActivity)).every(row=>row.actorId===actor),true);
  const {rows}=await client.query<{relrowsecurity:boolean}>("select relrowsecurity from pg_class where relname in ('entry_drafts','admin_activity') and relnamespace='public'::regnamespace");assert.equal(rows.length,2);assert.ok(rows.every(row=>row.relrowsecurity));
  console.log('Admin checks passed: verified allowlist, Markdown/JSON validation, private drafts, immutable publication, stale-edit rejection, restore, archive, loop publishing, evaluation preservation, audit trail, and RLS. Disposable data only.');
}finally{await client.close();}
